# Generated by Django 4.0.3 on 2022-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.EmailField(max_length=100)),
                ('domain_name', models.CharField(max_length=100)),
                ('mailbox', models.EmailField(max_length=100)),
                ('new_alias', models.EmailField(max_length=100)),
                ('old_alias', models.EmailField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('pnl', models.CharField(max_length=100)),
                ('winrate', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=100)),
                ('winloss', models.CharField(max_length=100)),
            ],
        ),
    ]
